import { type FrontendPageRegistryItem } from './authorization-contract'

export const frontendPageRegistry: FrontendPageRegistryItem[] = [
  {
    routePath: '/',
    title: '首页',
    menuPaths: ['/index'],
    componentKeys: ['index', 'dashboard/index'],
  },
  {
    routePath: '/system/user',
    title: '用户管理',
    menuPaths: ['/system/user'],
    componentKeys: ['system/user/index'],
    requiredPermissions: ['system:user:list'],
  },
  {
    routePath: '/system/role',
    title: '角色管理',
    menuPaths: ['/system/role'],
    componentKeys: ['system/role/index'],
    requiredPermissions: ['system:role:list'],
  },
  {
    routePath: '/system/post',
    title: '岗位管理',
    menuPaths: ['/system/post'],
    componentKeys: ['system/post/index'],
    requiredPermissions: ['system:post:list'],
  },
  {
    routePath: '/system/config',
    title: '参数设置',
    menuPaths: ['/system/config'],
    componentKeys: ['system/config/index'],
    requiredPermissions: ['system:config:list'],
  },
  {
    routePath: '/system/dict',
    title: '字典管理',
    menuPaths: ['/system/dict'],
    componentKeys: ['system/dict/index'],
    requiredPermissions: ['system:dict:list'],
  },
  {
    routePath: '/system/notice',
    title: '通知公告',
    menuPaths: ['/system/notice'],
    componentKeys: ['system/notice/index'],
    requiredPermissions: ['system:notice:list'],
  },
  {
    routePath: '/system/dept',
    title: '部门管理',
    menuPaths: ['/system/dept'],
    componentKeys: ['system/dept/index'],
    requiredPermissions: ['system:dept:list'],
  },
  {
    routePath: '/system/menu',
    title: '菜单管理',
    menuPaths: ['/system/menu'],
    componentKeys: ['system/menu/index'],
    requiredPermissions: ['system:menu:list'],
  },
  {
    routePath: '/monitor/online',
    title: '在线用户',
    menuPaths: ['/monitor/online'],
    componentKeys: ['monitor/online/index'],
    requiredPermissions: ['monitor:online:list'],
  },
  {
    routePath: '/monitor/logininfor',
    title: '登录日志',
    menuPaths: ['/monitor/logininfor'],
    componentKeys: ['monitor/logininfor/index'],
    requiredPermissions: ['monitor:logininfor:list'],
  },
  {
    routePath: '/monitor/operlog',
    title: '操作日志',
    menuPaths: ['/monitor/operlog'],
    componentKeys: ['monitor/operlog/index'],
    requiredPermissions: ['monitor:operlog:list'],
  },
  {
    routePath: '/monitor/job',
    title: '定时任务',
    menuPaths: ['/monitor/job'],
    componentKeys: ['monitor/job/index'],
    requiredPermissions: ['monitor:job:list'],
  },
  {
    routePath: '/monitor/server',
    title: '服务监控',
    menuPaths: ['/monitor/server'],
    componentKeys: ['monitor/server/index'],
    requiredPermissions: ['monitor:server:list'],
  },
  {
    routePath: '/monitor/cache',
    title: '缓存监控',
    menuPaths: ['/monitor/cache'],
    componentKeys: ['monitor/cache/index'],
    requiredPermissions: ['monitor:cache:list'],
  },
  {
    routePath: '/monitor/cacheList',
    title: '缓存列表',
    menuPaths: ['/monitor/cacheList'],
    componentKeys: ['monitor/cache/list'],
    requiredPermissions: ['monitor:cache:list'],
  },
]
