/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServerIndexRouteImport } from './routes/_authenticated/server/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedPostsIndexRouteImport } from './routes/_authenticated/posts/index'
import { Route as AuthenticatedOperlogIndexRouteImport } from './routes/_authenticated/operlog/index'
import { Route as AuthenticatedOnlineIndexRouteImport } from './routes/_authenticated/online/index'
import { Route as AuthenticatedNoticesIndexRouteImport } from './routes/_authenticated/notices/index'
import { Route as AuthenticatedMenusIndexRouteImport } from './routes/_authenticated/menus/index'
import { Route as AuthenticatedLogininforIndexRouteImport } from './routes/_authenticated/logininfor/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGenIndexRouteImport } from './routes/_authenticated/gen/index'
import { Route as AuthenticatedDictsIndexRouteImport } from './routes/_authenticated/dicts/index'
import { Route as AuthenticatedDeptsIndexRouteImport } from './routes/_authenticated/depts/index'
import { Route as AuthenticatedConfigsIndexRouteImport } from './routes/_authenticated/configs/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCacheIndexRouteImport } from './routes/_authenticated/cache/index'
import { Route as AuthenticatedCacheListIndexRouteImport } from './routes/_authenticated/cache-list/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedUserProfileRouteImport } from './routes/_authenticated/user/profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedToolGenIndexRouteImport } from './routes/_authenticated/tool/gen/index'
import { Route as AuthenticatedSystemUserIndexRouteImport } from './routes/_authenticated/system/user/index'
import { Route as AuthenticatedSystemRoleIndexRouteImport } from './routes/_authenticated/system/role/index'
import { Route as AuthenticatedSystemPostIndexRouteImport } from './routes/_authenticated/system/post/index'
import { Route as AuthenticatedSystemNoticeIndexRouteImport } from './routes/_authenticated/system/notice/index'
import { Route as AuthenticatedSystemMenuIndexRouteImport } from './routes/_authenticated/system/menu/index'
import { Route as AuthenticatedSystemDictIndexRouteImport } from './routes/_authenticated/system/dict/index'
import { Route as AuthenticatedSystemDeptIndexRouteImport } from './routes/_authenticated/system/dept/index'
import { Route as AuthenticatedSystemConfigIndexRouteImport } from './routes/_authenticated/system/config/index'
import { Route as AuthenticatedMonitorServerIndexRouteImport } from './routes/_authenticated/monitor/server/index'
import { Route as AuthenticatedMonitorOperlogIndexRouteImport } from './routes/_authenticated/monitor/operlog/index'
import { Route as AuthenticatedMonitorOnlineIndexRouteImport } from './routes/_authenticated/monitor/online/index'
import { Route as AuthenticatedMonitorLogininforIndexRouteImport } from './routes/_authenticated/monitor/logininfor/index'
import { Route as AuthenticatedMonitorJobIndexRouteImport } from './routes/_authenticated/monitor/job/index'
import { Route as AuthenticatedMonitorCacheListIndexRouteImport } from './routes/_authenticated/monitor/cacheList/index'
import { Route as AuthenticatedMonitorCacheIndexRouteImport } from './routes/_authenticated/monitor/cache/index'
import { Route as AuthenticatedToolGenEditIndexTableIdRouteImport } from './routes/_authenticated/tool/gen-edit/index/$tableId'
import { Route as AuthenticatedSystemUserAuthRoleUserIdRouteImport } from './routes/_authenticated/system/user-auth/role/$userId'
import { Route as AuthenticatedSystemRoleAuthUserRoleIdRouteImport } from './routes/_authenticated/system/role-auth/user/$roleId'
import { Route as AuthenticatedMonitorJobLogIndexJobIdRouteImport } from './routes/_authenticated/monitor/job-log/index/$jobId'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServerIndexRoute =
  AuthenticatedServerIndexRouteImport.update({
    id: '/server/',
    path: '/server/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsIndexRoute = AuthenticatedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperlogIndexRoute =
  AuthenticatedOperlogIndexRouteImport.update({
    id: '/operlog/',
    path: '/operlog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnlineIndexRoute =
  AuthenticatedOnlineIndexRouteImport.update({
    id: '/online/',
    path: '/online/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNoticesIndexRoute =
  AuthenticatedNoticesIndexRouteImport.update({
    id: '/notices/',
    path: '/notices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenusIndexRoute = AuthenticatedMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogininforIndexRoute =
  AuthenticatedLogininforIndexRouteImport.update({
    id: '/logininfor/',
    path: '/logininfor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenIndexRoute = AuthenticatedGenIndexRouteImport.update({
  id: '/gen/',
  path: '/gen/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDictsIndexRoute = AuthenticatedDictsIndexRouteImport.update({
  id: '/dicts/',
  path: '/dicts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeptsIndexRoute = AuthenticatedDeptsIndexRouteImport.update({
  id: '/depts/',
  path: '/depts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigsIndexRoute =
  AuthenticatedConfigsIndexRouteImport.update({
    id: '/configs/',
    path: '/configs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCacheIndexRoute = AuthenticatedCacheIndexRouteImport.update({
  id: '/cache/',
  path: '/cache/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCacheListIndexRoute =
  AuthenticatedCacheListIndexRouteImport.update({
    id: '/cache-list/',
    path: '/cache-list/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedUserProfileRoute =
  AuthenticatedUserProfileRouteImport.update({
    id: '/user/profile',
    path: '/user/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolGenIndexRoute =
  AuthenticatedToolGenIndexRouteImport.update({
    id: '/tool/gen/',
    path: '/tool/gen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUserIndexRoute =
  AuthenticatedSystemUserIndexRouteImport.update({
    id: '/system/user/',
    path: '/system/user/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRoleIndexRoute =
  AuthenticatedSystemRoleIndexRouteImport.update({
    id: '/system/role/',
    path: '/system/role/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemPostIndexRoute =
  AuthenticatedSystemPostIndexRouteImport.update({
    id: '/system/post/',
    path: '/system/post/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemNoticeIndexRoute =
  AuthenticatedSystemNoticeIndexRouteImport.update({
    id: '/system/notice/',
    path: '/system/notice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemMenuIndexRoute =
  AuthenticatedSystemMenuIndexRouteImport.update({
    id: '/system/menu/',
    path: '/system/menu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDictIndexRoute =
  AuthenticatedSystemDictIndexRouteImport.update({
    id: '/system/dict/',
    path: '/system/dict/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDeptIndexRoute =
  AuthenticatedSystemDeptIndexRouteImport.update({
    id: '/system/dept/',
    path: '/system/dept/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemConfigIndexRoute =
  AuthenticatedSystemConfigIndexRouteImport.update({
    id: '/system/config/',
    path: '/system/config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorServerIndexRoute =
  AuthenticatedMonitorServerIndexRouteImport.update({
    id: '/monitor/server/',
    path: '/monitor/server/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorOperlogIndexRoute =
  AuthenticatedMonitorOperlogIndexRouteImport.update({
    id: '/monitor/operlog/',
    path: '/monitor/operlog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorOnlineIndexRoute =
  AuthenticatedMonitorOnlineIndexRouteImport.update({
    id: '/monitor/online/',
    path: '/monitor/online/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorLogininforIndexRoute =
  AuthenticatedMonitorLogininforIndexRouteImport.update({
    id: '/monitor/logininfor/',
    path: '/monitor/logininfor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorJobIndexRoute =
  AuthenticatedMonitorJobIndexRouteImport.update({
    id: '/monitor/job/',
    path: '/monitor/job/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorCacheListIndexRoute =
  AuthenticatedMonitorCacheListIndexRouteImport.update({
    id: '/monitor/cacheList/',
    path: '/monitor/cacheList/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorCacheIndexRoute =
  AuthenticatedMonitorCacheIndexRouteImport.update({
    id: '/monitor/cache/',
    path: '/monitor/cache/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolGenEditIndexTableIdRoute =
  AuthenticatedToolGenEditIndexTableIdRouteImport.update({
    id: '/tool/gen-edit/index/$tableId',
    path: '/tool/gen-edit/index/$tableId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUserAuthRoleUserIdRoute =
  AuthenticatedSystemUserAuthRoleUserIdRouteImport.update({
    id: '/system/user-auth/role/$userId',
    path: '/system/user-auth/role/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRoleAuthUserRoleIdRoute =
  AuthenticatedSystemRoleAuthUserRoleIdRouteImport.update({
    id: '/system/role-auth/user/$roleId',
    path: '/system/role-auth/user/$roleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorJobLogIndexJobIdRoute =
  AuthenticatedMonitorJobLogIndexJobIdRouteImport.update({
    id: '/monitor/job-log/index/$jobId',
    path: '/monitor/job-log/index/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/user/profile': typeof AuthenticatedUserProfileRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/cache-list/': typeof AuthenticatedCacheListIndexRoute
  '/cache/': typeof AuthenticatedCacheIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/configs/': typeof AuthenticatedConfigsIndexRoute
  '/depts/': typeof AuthenticatedDeptsIndexRoute
  '/dicts/': typeof AuthenticatedDictsIndexRoute
  '/gen/': typeof AuthenticatedGenIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/logininfor/': typeof AuthenticatedLogininforIndexRoute
  '/menus/': typeof AuthenticatedMenusIndexRoute
  '/notices/': typeof AuthenticatedNoticesIndexRoute
  '/online/': typeof AuthenticatedOnlineIndexRoute
  '/operlog/': typeof AuthenticatedOperlogIndexRoute
  '/posts/': typeof AuthenticatedPostsIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/server/': typeof AuthenticatedServerIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/monitor/cache/': typeof AuthenticatedMonitorCacheIndexRoute
  '/monitor/cacheList/': typeof AuthenticatedMonitorCacheListIndexRoute
  '/monitor/job/': typeof AuthenticatedMonitorJobIndexRoute
  '/monitor/logininfor/': typeof AuthenticatedMonitorLogininforIndexRoute
  '/monitor/online/': typeof AuthenticatedMonitorOnlineIndexRoute
  '/monitor/operlog/': typeof AuthenticatedMonitorOperlogIndexRoute
  '/monitor/server/': typeof AuthenticatedMonitorServerIndexRoute
  '/system/config/': typeof AuthenticatedSystemConfigIndexRoute
  '/system/dept/': typeof AuthenticatedSystemDeptIndexRoute
  '/system/dict/': typeof AuthenticatedSystemDictIndexRoute
  '/system/menu/': typeof AuthenticatedSystemMenuIndexRoute
  '/system/notice/': typeof AuthenticatedSystemNoticeIndexRoute
  '/system/post/': typeof AuthenticatedSystemPostIndexRoute
  '/system/role/': typeof AuthenticatedSystemRoleIndexRoute
  '/system/user/': typeof AuthenticatedSystemUserIndexRoute
  '/tool/gen/': typeof AuthenticatedToolGenIndexRoute
  '/monitor/job-log/index/$jobId': typeof AuthenticatedMonitorJobLogIndexJobIdRoute
  '/system/role-auth/user/$roleId': typeof AuthenticatedSystemRoleAuthUserRoleIdRoute
  '/system/user-auth/role/$userId': typeof AuthenticatedSystemUserAuthRoleUserIdRoute
  '/tool/gen-edit/index/$tableId': typeof AuthenticatedToolGenEditIndexTableIdRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/user/profile': typeof AuthenticatedUserProfileRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/cache-list': typeof AuthenticatedCacheListIndexRoute
  '/cache': typeof AuthenticatedCacheIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/configs': typeof AuthenticatedConfigsIndexRoute
  '/depts': typeof AuthenticatedDeptsIndexRoute
  '/dicts': typeof AuthenticatedDictsIndexRoute
  '/gen': typeof AuthenticatedGenIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/logininfor': typeof AuthenticatedLogininforIndexRoute
  '/menus': typeof AuthenticatedMenusIndexRoute
  '/notices': typeof AuthenticatedNoticesIndexRoute
  '/online': typeof AuthenticatedOnlineIndexRoute
  '/operlog': typeof AuthenticatedOperlogIndexRoute
  '/posts': typeof AuthenticatedPostsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/server': typeof AuthenticatedServerIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/monitor/cache': typeof AuthenticatedMonitorCacheIndexRoute
  '/monitor/cacheList': typeof AuthenticatedMonitorCacheListIndexRoute
  '/monitor/job': typeof AuthenticatedMonitorJobIndexRoute
  '/monitor/logininfor': typeof AuthenticatedMonitorLogininforIndexRoute
  '/monitor/online': typeof AuthenticatedMonitorOnlineIndexRoute
  '/monitor/operlog': typeof AuthenticatedMonitorOperlogIndexRoute
  '/monitor/server': typeof AuthenticatedMonitorServerIndexRoute
  '/system/config': typeof AuthenticatedSystemConfigIndexRoute
  '/system/dept': typeof AuthenticatedSystemDeptIndexRoute
  '/system/dict': typeof AuthenticatedSystemDictIndexRoute
  '/system/menu': typeof AuthenticatedSystemMenuIndexRoute
  '/system/notice': typeof AuthenticatedSystemNoticeIndexRoute
  '/system/post': typeof AuthenticatedSystemPostIndexRoute
  '/system/role': typeof AuthenticatedSystemRoleIndexRoute
  '/system/user': typeof AuthenticatedSystemUserIndexRoute
  '/tool/gen': typeof AuthenticatedToolGenIndexRoute
  '/monitor/job-log/index/$jobId': typeof AuthenticatedMonitorJobLogIndexJobIdRoute
  '/system/role-auth/user/$roleId': typeof AuthenticatedSystemRoleAuthUserRoleIdRoute
  '/system/user-auth/role/$userId': typeof AuthenticatedSystemUserAuthRoleUserIdRoute
  '/tool/gen-edit/index/$tableId': typeof AuthenticatedToolGenEditIndexTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/user/profile': typeof AuthenticatedUserProfileRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/cache-list/': typeof AuthenticatedCacheListIndexRoute
  '/_authenticated/cache/': typeof AuthenticatedCacheIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/configs/': typeof AuthenticatedConfigsIndexRoute
  '/_authenticated/depts/': typeof AuthenticatedDeptsIndexRoute
  '/_authenticated/dicts/': typeof AuthenticatedDictsIndexRoute
  '/_authenticated/gen/': typeof AuthenticatedGenIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/logininfor/': typeof AuthenticatedLogininforIndexRoute
  '/_authenticated/menus/': typeof AuthenticatedMenusIndexRoute
  '/_authenticated/notices/': typeof AuthenticatedNoticesIndexRoute
  '/_authenticated/online/': typeof AuthenticatedOnlineIndexRoute
  '/_authenticated/operlog/': typeof AuthenticatedOperlogIndexRoute
  '/_authenticated/posts/': typeof AuthenticatedPostsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/server/': typeof AuthenticatedServerIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/monitor/cache/': typeof AuthenticatedMonitorCacheIndexRoute
  '/_authenticated/monitor/cacheList/': typeof AuthenticatedMonitorCacheListIndexRoute
  '/_authenticated/monitor/job/': typeof AuthenticatedMonitorJobIndexRoute
  '/_authenticated/monitor/logininfor/': typeof AuthenticatedMonitorLogininforIndexRoute
  '/_authenticated/monitor/online/': typeof AuthenticatedMonitorOnlineIndexRoute
  '/_authenticated/monitor/operlog/': typeof AuthenticatedMonitorOperlogIndexRoute
  '/_authenticated/monitor/server/': typeof AuthenticatedMonitorServerIndexRoute
  '/_authenticated/system/config/': typeof AuthenticatedSystemConfigIndexRoute
  '/_authenticated/system/dept/': typeof AuthenticatedSystemDeptIndexRoute
  '/_authenticated/system/dict/': typeof AuthenticatedSystemDictIndexRoute
  '/_authenticated/system/menu/': typeof AuthenticatedSystemMenuIndexRoute
  '/_authenticated/system/notice/': typeof AuthenticatedSystemNoticeIndexRoute
  '/_authenticated/system/post/': typeof AuthenticatedSystemPostIndexRoute
  '/_authenticated/system/role/': typeof AuthenticatedSystemRoleIndexRoute
  '/_authenticated/system/user/': typeof AuthenticatedSystemUserIndexRoute
  '/_authenticated/tool/gen/': typeof AuthenticatedToolGenIndexRoute
  '/_authenticated/monitor/job-log/index/$jobId': typeof AuthenticatedMonitorJobLogIndexJobIdRoute
  '/_authenticated/system/role-auth/user/$roleId': typeof AuthenticatedSystemRoleAuthUserRoleIdRoute
  '/_authenticated/system/user-auth/role/$userId': typeof AuthenticatedSystemUserAuthRoleUserIdRoute
  '/_authenticated/tool/gen-edit/index/$tableId': typeof AuthenticatedToolGenEditIndexTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/user/profile'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/cache-list/'
    | '/cache/'
    | '/chats/'
    | '/configs/'
    | '/depts/'
    | '/dicts/'
    | '/gen/'
    | '/help-center/'
    | '/logininfor/'
    | '/menus/'
    | '/notices/'
    | '/online/'
    | '/operlog/'
    | '/posts/'
    | '/roles/'
    | '/server/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/monitor/cache/'
    | '/monitor/cacheList/'
    | '/monitor/job/'
    | '/monitor/logininfor/'
    | '/monitor/online/'
    | '/monitor/operlog/'
    | '/monitor/server/'
    | '/system/config/'
    | '/system/dept/'
    | '/system/dict/'
    | '/system/menu/'
    | '/system/notice/'
    | '/system/post/'
    | '/system/role/'
    | '/system/user/'
    | '/tool/gen/'
    | '/monitor/job-log/index/$jobId'
    | '/system/role-auth/user/$roleId'
    | '/system/user-auth/role/$userId'
    | '/tool/gen-edit/index/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/user/profile'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/cache-list'
    | '/cache'
    | '/chats'
    | '/configs'
    | '/depts'
    | '/dicts'
    | '/gen'
    | '/help-center'
    | '/logininfor'
    | '/menus'
    | '/notices'
    | '/online'
    | '/operlog'
    | '/posts'
    | '/roles'
    | '/server'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/monitor/cache'
    | '/monitor/cacheList'
    | '/monitor/job'
    | '/monitor/logininfor'
    | '/monitor/online'
    | '/monitor/operlog'
    | '/monitor/server'
    | '/system/config'
    | '/system/dept'
    | '/system/dict'
    | '/system/menu'
    | '/system/notice'
    | '/system/post'
    | '/system/role'
    | '/system/user'
    | '/tool/gen'
    | '/monitor/job-log/index/$jobId'
    | '/system/role-auth/user/$roleId'
    | '/system/user-auth/role/$userId'
    | '/tool/gen-edit/index/$tableId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/user/profile'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/cache-list/'
    | '/_authenticated/cache/'
    | '/_authenticated/chats/'
    | '/_authenticated/configs/'
    | '/_authenticated/depts/'
    | '/_authenticated/dicts/'
    | '/_authenticated/gen/'
    | '/_authenticated/help-center/'
    | '/_authenticated/logininfor/'
    | '/_authenticated/menus/'
    | '/_authenticated/notices/'
    | '/_authenticated/online/'
    | '/_authenticated/operlog/'
    | '/_authenticated/posts/'
    | '/_authenticated/roles/'
    | '/_authenticated/server/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/monitor/cache/'
    | '/_authenticated/monitor/cacheList/'
    | '/_authenticated/monitor/job/'
    | '/_authenticated/monitor/logininfor/'
    | '/_authenticated/monitor/online/'
    | '/_authenticated/monitor/operlog/'
    | '/_authenticated/monitor/server/'
    | '/_authenticated/system/config/'
    | '/_authenticated/system/dept/'
    | '/_authenticated/system/dict/'
    | '/_authenticated/system/menu/'
    | '/_authenticated/system/notice/'
    | '/_authenticated/system/post/'
    | '/_authenticated/system/role/'
    | '/_authenticated/system/user/'
    | '/_authenticated/tool/gen/'
    | '/_authenticated/monitor/job-log/index/$jobId'
    | '/_authenticated/system/role-auth/user/$roleId'
    | '/_authenticated/system/user-auth/role/$userId'
    | '/_authenticated/tool/gen-edit/index/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/server/': {
      id: '/_authenticated/server/'
      path: '/server'
      fullPath: '/server/'
      preLoaderRoute: typeof AuthenticatedServerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/': {
      id: '/_authenticated/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthenticatedPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operlog/': {
      id: '/_authenticated/operlog/'
      path: '/operlog'
      fullPath: '/operlog/'
      preLoaderRoute: typeof AuthenticatedOperlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online/': {
      id: '/_authenticated/online/'
      path: '/online'
      fullPath: '/online/'
      preLoaderRoute: typeof AuthenticatedOnlineIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notices/': {
      id: '/_authenticated/notices/'
      path: '/notices'
      fullPath: '/notices/'
      preLoaderRoute: typeof AuthenticatedNoticesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menus/': {
      id: '/_authenticated/menus/'
      path: '/menus'
      fullPath: '/menus/'
      preLoaderRoute: typeof AuthenticatedMenusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logininfor/': {
      id: '/_authenticated/logininfor/'
      path: '/logininfor'
      fullPath: '/logininfor/'
      preLoaderRoute: typeof AuthenticatedLogininforIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gen/': {
      id: '/_authenticated/gen/'
      path: '/gen'
      fullPath: '/gen/'
      preLoaderRoute: typeof AuthenticatedGenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dicts/': {
      id: '/_authenticated/dicts/'
      path: '/dicts'
      fullPath: '/dicts/'
      preLoaderRoute: typeof AuthenticatedDictsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depts/': {
      id: '/_authenticated/depts/'
      path: '/depts'
      fullPath: '/depts/'
      preLoaderRoute: typeof AuthenticatedDeptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configs/': {
      id: '/_authenticated/configs/'
      path: '/configs'
      fullPath: '/configs/'
      preLoaderRoute: typeof AuthenticatedConfigsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cache/': {
      id: '/_authenticated/cache/'
      path: '/cache'
      fullPath: '/cache/'
      preLoaderRoute: typeof AuthenticatedCacheIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cache-list/': {
      id: '/_authenticated/cache-list/'
      path: '/cache-list'
      fullPath: '/cache-list/'
      preLoaderRoute: typeof AuthenticatedCacheListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/user/profile': {
      id: '/_authenticated/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof AuthenticatedUserProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool/gen/': {
      id: '/_authenticated/tool/gen/'
      path: '/tool/gen'
      fullPath: '/tool/gen/'
      preLoaderRoute: typeof AuthenticatedToolGenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/user/': {
      id: '/_authenticated/system/user/'
      path: '/system/user'
      fullPath: '/system/user/'
      preLoaderRoute: typeof AuthenticatedSystemUserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/role/': {
      id: '/_authenticated/system/role/'
      path: '/system/role'
      fullPath: '/system/role/'
      preLoaderRoute: typeof AuthenticatedSystemRoleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/post/': {
      id: '/_authenticated/system/post/'
      path: '/system/post'
      fullPath: '/system/post/'
      preLoaderRoute: typeof AuthenticatedSystemPostIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/notice/': {
      id: '/_authenticated/system/notice/'
      path: '/system/notice'
      fullPath: '/system/notice/'
      preLoaderRoute: typeof AuthenticatedSystemNoticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/menu/': {
      id: '/_authenticated/system/menu/'
      path: '/system/menu'
      fullPath: '/system/menu/'
      preLoaderRoute: typeof AuthenticatedSystemMenuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/dict/': {
      id: '/_authenticated/system/dict/'
      path: '/system/dict'
      fullPath: '/system/dict/'
      preLoaderRoute: typeof AuthenticatedSystemDictIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/dept/': {
      id: '/_authenticated/system/dept/'
      path: '/system/dept'
      fullPath: '/system/dept/'
      preLoaderRoute: typeof AuthenticatedSystemDeptIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/config/': {
      id: '/_authenticated/system/config/'
      path: '/system/config'
      fullPath: '/system/config/'
      preLoaderRoute: typeof AuthenticatedSystemConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/server/': {
      id: '/_authenticated/monitor/server/'
      path: '/monitor/server'
      fullPath: '/monitor/server/'
      preLoaderRoute: typeof AuthenticatedMonitorServerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/operlog/': {
      id: '/_authenticated/monitor/operlog/'
      path: '/monitor/operlog'
      fullPath: '/monitor/operlog/'
      preLoaderRoute: typeof AuthenticatedMonitorOperlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/online/': {
      id: '/_authenticated/monitor/online/'
      path: '/monitor/online'
      fullPath: '/monitor/online/'
      preLoaderRoute: typeof AuthenticatedMonitorOnlineIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/logininfor/': {
      id: '/_authenticated/monitor/logininfor/'
      path: '/monitor/logininfor'
      fullPath: '/monitor/logininfor/'
      preLoaderRoute: typeof AuthenticatedMonitorLogininforIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/job/': {
      id: '/_authenticated/monitor/job/'
      path: '/monitor/job'
      fullPath: '/monitor/job/'
      preLoaderRoute: typeof AuthenticatedMonitorJobIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/cacheList/': {
      id: '/_authenticated/monitor/cacheList/'
      path: '/monitor/cacheList'
      fullPath: '/monitor/cacheList/'
      preLoaderRoute: typeof AuthenticatedMonitorCacheListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/cache/': {
      id: '/_authenticated/monitor/cache/'
      path: '/monitor/cache'
      fullPath: '/monitor/cache/'
      preLoaderRoute: typeof AuthenticatedMonitorCacheIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool/gen-edit/index/$tableId': {
      id: '/_authenticated/tool/gen-edit/index/$tableId'
      path: '/tool/gen-edit/index/$tableId'
      fullPath: '/tool/gen-edit/index/$tableId'
      preLoaderRoute: typeof AuthenticatedToolGenEditIndexTableIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/user-auth/role/$userId': {
      id: '/_authenticated/system/user-auth/role/$userId'
      path: '/system/user-auth/role/$userId'
      fullPath: '/system/user-auth/role/$userId'
      preLoaderRoute: typeof AuthenticatedSystemUserAuthRoleUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/role-auth/user/$roleId': {
      id: '/_authenticated/system/role-auth/user/$roleId'
      path: '/system/role-auth/user/$roleId'
      fullPath: '/system/role-auth/user/$roleId'
      preLoaderRoute: typeof AuthenticatedSystemRoleAuthUserRoleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor/job-log/index/$jobId': {
      id: '/_authenticated/monitor/job-log/index/$jobId'
      path: '/monitor/job-log/index/$jobId'
      fullPath: '/monitor/job-log/index/$jobId'
      preLoaderRoute: typeof AuthenticatedMonitorJobLogIndexJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedUserProfileRoute: typeof AuthenticatedUserProfileRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedCacheListIndexRoute: typeof AuthenticatedCacheListIndexRoute
  AuthenticatedCacheIndexRoute: typeof AuthenticatedCacheIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedConfigsIndexRoute: typeof AuthenticatedConfigsIndexRoute
  AuthenticatedDeptsIndexRoute: typeof AuthenticatedDeptsIndexRoute
  AuthenticatedDictsIndexRoute: typeof AuthenticatedDictsIndexRoute
  AuthenticatedGenIndexRoute: typeof AuthenticatedGenIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLogininforIndexRoute: typeof AuthenticatedLogininforIndexRoute
  AuthenticatedMenusIndexRoute: typeof AuthenticatedMenusIndexRoute
  AuthenticatedNoticesIndexRoute: typeof AuthenticatedNoticesIndexRoute
  AuthenticatedOnlineIndexRoute: typeof AuthenticatedOnlineIndexRoute
  AuthenticatedOperlogIndexRoute: typeof AuthenticatedOperlogIndexRoute
  AuthenticatedPostsIndexRoute: typeof AuthenticatedPostsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedServerIndexRoute: typeof AuthenticatedServerIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedMonitorCacheIndexRoute: typeof AuthenticatedMonitorCacheIndexRoute
  AuthenticatedMonitorCacheListIndexRoute: typeof AuthenticatedMonitorCacheListIndexRoute
  AuthenticatedMonitorJobIndexRoute: typeof AuthenticatedMonitorJobIndexRoute
  AuthenticatedMonitorLogininforIndexRoute: typeof AuthenticatedMonitorLogininforIndexRoute
  AuthenticatedMonitorOnlineIndexRoute: typeof AuthenticatedMonitorOnlineIndexRoute
  AuthenticatedMonitorOperlogIndexRoute: typeof AuthenticatedMonitorOperlogIndexRoute
  AuthenticatedMonitorServerIndexRoute: typeof AuthenticatedMonitorServerIndexRoute
  AuthenticatedSystemConfigIndexRoute: typeof AuthenticatedSystemConfigIndexRoute
  AuthenticatedSystemDeptIndexRoute: typeof AuthenticatedSystemDeptIndexRoute
  AuthenticatedSystemDictIndexRoute: typeof AuthenticatedSystemDictIndexRoute
  AuthenticatedSystemMenuIndexRoute: typeof AuthenticatedSystemMenuIndexRoute
  AuthenticatedSystemNoticeIndexRoute: typeof AuthenticatedSystemNoticeIndexRoute
  AuthenticatedSystemPostIndexRoute: typeof AuthenticatedSystemPostIndexRoute
  AuthenticatedSystemRoleIndexRoute: typeof AuthenticatedSystemRoleIndexRoute
  AuthenticatedSystemUserIndexRoute: typeof AuthenticatedSystemUserIndexRoute
  AuthenticatedToolGenIndexRoute: typeof AuthenticatedToolGenIndexRoute
  AuthenticatedMonitorJobLogIndexJobIdRoute: typeof AuthenticatedMonitorJobLogIndexJobIdRoute
  AuthenticatedSystemRoleAuthUserRoleIdRoute: typeof AuthenticatedSystemRoleAuthUserRoleIdRoute
  AuthenticatedSystemUserAuthRoleUserIdRoute: typeof AuthenticatedSystemUserAuthRoleUserIdRoute
  AuthenticatedToolGenEditIndexTableIdRoute: typeof AuthenticatedToolGenEditIndexTableIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedUserProfileRoute: AuthenticatedUserProfileRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedCacheListIndexRoute: AuthenticatedCacheListIndexRoute,
  AuthenticatedCacheIndexRoute: AuthenticatedCacheIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedConfigsIndexRoute: AuthenticatedConfigsIndexRoute,
  AuthenticatedDeptsIndexRoute: AuthenticatedDeptsIndexRoute,
  AuthenticatedDictsIndexRoute: AuthenticatedDictsIndexRoute,
  AuthenticatedGenIndexRoute: AuthenticatedGenIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLogininforIndexRoute: AuthenticatedLogininforIndexRoute,
  AuthenticatedMenusIndexRoute: AuthenticatedMenusIndexRoute,
  AuthenticatedNoticesIndexRoute: AuthenticatedNoticesIndexRoute,
  AuthenticatedOnlineIndexRoute: AuthenticatedOnlineIndexRoute,
  AuthenticatedOperlogIndexRoute: AuthenticatedOperlogIndexRoute,
  AuthenticatedPostsIndexRoute: AuthenticatedPostsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedServerIndexRoute: AuthenticatedServerIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedMonitorCacheIndexRoute: AuthenticatedMonitorCacheIndexRoute,
  AuthenticatedMonitorCacheListIndexRoute:
    AuthenticatedMonitorCacheListIndexRoute,
  AuthenticatedMonitorJobIndexRoute: AuthenticatedMonitorJobIndexRoute,
  AuthenticatedMonitorLogininforIndexRoute:
    AuthenticatedMonitorLogininforIndexRoute,
  AuthenticatedMonitorOnlineIndexRoute: AuthenticatedMonitorOnlineIndexRoute,
  AuthenticatedMonitorOperlogIndexRoute: AuthenticatedMonitorOperlogIndexRoute,
  AuthenticatedMonitorServerIndexRoute: AuthenticatedMonitorServerIndexRoute,
  AuthenticatedSystemConfigIndexRoute: AuthenticatedSystemConfigIndexRoute,
  AuthenticatedSystemDeptIndexRoute: AuthenticatedSystemDeptIndexRoute,
  AuthenticatedSystemDictIndexRoute: AuthenticatedSystemDictIndexRoute,
  AuthenticatedSystemMenuIndexRoute: AuthenticatedSystemMenuIndexRoute,
  AuthenticatedSystemNoticeIndexRoute: AuthenticatedSystemNoticeIndexRoute,
  AuthenticatedSystemPostIndexRoute: AuthenticatedSystemPostIndexRoute,
  AuthenticatedSystemRoleIndexRoute: AuthenticatedSystemRoleIndexRoute,
  AuthenticatedSystemUserIndexRoute: AuthenticatedSystemUserIndexRoute,
  AuthenticatedToolGenIndexRoute: AuthenticatedToolGenIndexRoute,
  AuthenticatedMonitorJobLogIndexJobIdRoute:
    AuthenticatedMonitorJobLogIndexJobIdRoute,
  AuthenticatedSystemRoleAuthUserRoleIdRoute:
    AuthenticatedSystemRoleAuthUserRoleIdRoute,
  AuthenticatedSystemUserAuthRoleUserIdRoute:
    AuthenticatedSystemUserAuthRoleUserIdRoute,
  AuthenticatedToolGenEditIndexTableIdRoute:
    AuthenticatedToolGenEditIndexTableIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
